### DISCUSSION TITLE
v1.1.1

### DISCUSSION THREAD

**Discussion by james0r** [james0r/slayed#13] [Announcements]
- Bumped Vite to v5
- Bumped Vite plugins
- Changed Shopify Vite config option to now use the default vite-tag.liquid snippet to avoid possible bug there

<hr /><em>This discussion was created from the release <a href='https://github.com/james0r/slayed/releases/tag/v1.1.1'>v1.1.1</a>.</em>

**Comment by 1dagranholm** [comment]
Hi! I have a problem with the npm/vite/shopify cli setup in this theme which affects my workflow.

I have connected the theme to my shopify store through Shopify's Github App. I have a github repo for the project with two branches, develop and master, which corresponds to development environment and production anvironment in my shopify.theme.toml. 

I run Shopify CLI 3.0.

As there's no theme editor for local environment any longer in Shopify CLI 3.0, I have to use the editor for the deleopment theme in my Shopify store. But as I work on the sections/snippets/styling with Tailwind etc in my local environment the files are overriden all the time. Or edits from Shopify editor isn't updated locally. 

Do you have any recommendations in workflow using your theme?

**Reply by james0r** [reply]
@1dagranholm 

I totally forgot about the local theme editor and I never used it much anyways.

I think a common approach would be to just duplicate your production theme to something like **development**, grab the theme id and use that for deployments and dev by adding it to your shopify.theme.toml.

```toml
[environments.development]
store = "slayed-starter"
theme = "<dev theme id>"

[environments.production]
store = "slayed-starter"
theme = "<prod theme id>"
ignore = ["templates/*", "config/*"]
```

You can play around with `ignore = ["templates/*", "config/*"]` and decide if you want to sync changes for production or not.

Is that what you mean? Have you tried that?
